%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% This file was autogenerated by PaperShell v3 
%% https://github.com/sylvainhalle/PaperShell
%% DO NOT EDIT!
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[conference]{sty/ieeetran/IEEEtran}

% Usual packages
\usepackage[utf8]{inputenc}            % UTF-8 input encoding
\usepackage[T1]{fontenc}               % Type1 fonts
\usepackage[english]{babel}            % Hyphenation
\usepackage{graphicx}                  % Import graphics
\usepackage{cite}                      % Better handling of citations
\usepackage{comment}                   % To comment out blocks of text
\usepackage{flushend}                  % To balance columns on last page
\usepackage{microtype}                 % Better typesetting
\usepackage[scaled]{helvet}            % Scale Helvetica
\usepackage[bookmarks=false]{hyperref} % Better handling of references in PDFs

% Title
\title{<%= title %>%
}


\author{%
<%
local authors      = authors      or {}
local institutions = institutions or {}

-- Group author names by institution index
local grouped = {}
for _, a in ipairs(authors) do
  local inst_idx = a.institution  -- should be 1, 2, ...
  if inst_idx ~= nil then
    local g = grouped[inst_idx]
    if not g then
      g = {}
      grouped[inst_idx] = g
    end
    table.insert(g, a.name)
  end
end

-- Now print one block per institution, in order
for inst_idx, inst in ipairs(institutions) do
  local names = grouped[inst_idx]
  if names and #names > 0 then
    local name_str = table.concat(names, ", ")
%>
\IEEEauthorblockN{<%= name_str %>}
\IEEEauthorblockA{<%= inst.name %>}


<%
  end
end
%>
}


\input{includes.tex}
\usepackage{newtxtext,newtxmath} % Times with math support. Must be placed here to avoid clash if amsthm is loaded in includes

% Default path for graphicspath
\graphicspath{fig/}

\begin{document}

% Authors and affiliations
<% for i, a in ipairs(authors) do
  texio.write_nl("Author " .. i .. ": " .. (a.name or "?"))
end %>

\maketitle

\begin{abstract}
\input{abstract.tex}
\end{abstract}

% Fixing bug in the definition of \\markboth in IEEEtran class
% See http://tex.stackexchange.com/a/88864
\makeatletter
\let\l@ENGLISH\l@english
\makeatother
% :mode=latex: