<?php
/**************************************************************************
  A Flexible LaTeX Article Environment
  Copyright (C) 2015-2016  Sylvain Hallé

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **************************************************************************/

// Version
$version_string = "1.7.1";
$autogen_comment = "%% This file was autogenerated by PaperShell v$version_string on ".date("Y-m-d H:i:s")."\n%% https://github.com/sylvainhalle/PaperShell\n%% DO NOT EDIT!";

// Read author-title file
$input_filename = "authors.txt";
$out_folder = "Source/";

// Read default config settings. All these settings can be modified with
// settings.inc.php. Do not modify them here.
$config = array(
	"tex-name"       => "paper",
	"bib-name"       => "paper",
	"short-title"    => "",
	"point-size"     => null,
	"abstract"       => true,
	"journal-name"   => "Nuclear Physics B",
	"volume"         => 9,
	"number"         => 4,
	"article-number" => 39,
	"conference"     => "OUTATIME '55",
	"conference-loc" => "November 5--12, 1955, Hill Valley, CA",
	"copyright"      => "0-89791-88-6/97/05",
	"year"           => date("Y"),
	"month"          => date("m"),
	"doi"            => "0000001.0000001",
	"isbn"           => "123-4567-24-567/08/06",
	"issn"           => "1234-56789",
	"fix-acm"        => false,
	"use-times"      => false,
	"bib-style"      => "",
	"graphicspath"   => array("fig/"),
	"microtype"      => true,
	"corr-addr"      => "Hill Valley University, CA",
	"doublespace"    => false
);
if (file_exists("settings.inc.php"))
{
  include("settings.inc.php");
}
$lines = explode("\n", file_get_contents($input_filename));

{ // Parse file {{{
  $has_title = false;
  $current_affiliation = 1;
  $title = "";
  $affiliations = array();
  $authors = array();
  foreach ($lines as $line)
  {
    $line = trim($line);
    if (empty($line) || $line[0] === "#")
    {
      continue;
    }
    if (!$has_title)
    {
      $title = $line;
      $has_title = true;
      continue;
    }
    $matches = array();
    if (preg_match("/^(.*)\\((\\d+)\\)$/", $line, $matches))
    {
      $authors[trim($matches[1])] = trim($matches[2]);
    }
    elseif (preg_match("/^\\d+$/", $line))
    {
      $current_affiliation = $line;
    }
    else
    {
      if (!isset($affiliations[$current_affiliation]))
      {
        $affiliations[$current_affiliation] = array();
      }
      $affiliations[$current_affiliation][] = $line;
    }
  }
} // }}}

// Basic info
echo "PaperShell v".$version_string."\nA nice and flexible template environment for papers written in LaTeX\n(C) 2015-2016 Sylvain Hallé, Université du Québec à Chicoutimi\nhttps://github.com/sylvainhalle/PaperShell\n";

// Now that authors and affiliations are known, generate the preamble
// specific to each stylesheet

// Set a point-size, or use the default if not specified
$point_size_string = $config["point-size"] === null ? "" : $config["point-size"]."pt";
$point_size_string_comma = $config["point-size"] === null ? "" : ",".$config["point-size"]."pt";

// Microtype enabled?
$microtype_string ="";
if ($config["microtype"])
{
  $microtype_string = "\n\usepackage{microtype}       % Better handling of typo";
}

{ // Springer LNCS {{{
  
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "splncs03" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[{$point_size_string}]{llncs}

% Usual packages
\usepackage[utf8]{inputenc}  % UTF-8 input encoding
\usepackage[T1]{fontenc}     % Type1 fonts{$microtype_string}
\usepackage[english]{babel}  % Hyphenation
\usepackage{graphicx}        % Import graphics
\usepackage{cite}            % Better handling of citations
\usepackage{hyperref}        % Better handling of references in PDFs
\usepackage{comment}         % To comment out blocks of text
EOD;

  if ($config["use-times"])
  {
    $out .= "\n\\usepackage{mathptmx}        % Times font with math support\n";
  }
  else
  {
    $out .= "\n\\usepackage{lmodern}         % Improved Computer Modern font\n";
  }

  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n\n";
  
  $out .= "% Authors and affiliations\n";
  $out .= "\\author{";
  $first = true;
  foreach ($authors as $name => $aff)
  {
    if ($first)
    {
      $first = false;
    }
    else
    {
      $out .= " \\and ";
    }
    $out .= $name.(count($affiliations) < 2 ? "" : "\\inst{".$aff."}");
  }
  $out .= "}\n";
  $out .= "\\institute{%\n";
  $first = true;
  foreach ($affiliations as $key => $lines)
  {
    if ($first)
    {
      $first = false;
    }
    else
    {
      $out .= "\\and\n";
    }
    $out .= implode(" \\\\\n", $lines);
  }
  $out .= "}\n\n";
  $out .= "\\input{includes.tex}\n\n";
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= "\\begin{document}\n\n";
  $out .= "\\maketitle\n";
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  file_put_contents($out_folder."preamble-lncs.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  $out .= "\\bibliography{".$config["bib-name"]."}\n";
  $out .= "\\input{appendices.tex}\n";
  $out .= "\\end{document}\n";
  file_put_contents($out_folder."postamble-lncs.inc.tex", $out);
} // }}}

{ // IEEE Conference Proceedings {{{
  
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "abbrv" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[conference{$point_size_string_comma}]{IEEEtran}

% Usual packages
\usepackage[utf8]{inputenc}  % UTF-8 input encoding
\usepackage[T1]{fontenc}     % Type1 fonts
\usepackage{mathptmx}        % Times with math support{$microtype_string}
\usepackage[english]{babel}  % Hyphenation
\usepackage{graphicx}        % Import graphics
\usepackage{cite}            % Better handling of citations
\usepackage{hyperref}        % Better handling of references in PDFs
\usepackage{comment}         % To comment out blocks of text
EOD;

  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n\n";
  
  // Group all authors with same affiliation
  $authors_aff = array();
  foreach ($authors as $name => $aff)
  {
    if (!isset($authors_aff[$aff]))
    {
      $authors_aff[$aff] = array();
    }
    $authors_aff[$aff][] = $name;
  }
  $out .= "% Authors and affiliations\n";
  $out .= "\\author{%\n";
  foreach ($authors_aff as $aff => $names)
  {
    $first = true;
    $out .= "\\IEEEauthorblockN{";
    foreach ($names as $name)
    {
      if ($first)
      {
        $first = false;
      }
      else
      {
        $out .= ", ";
      }
      $out .= $name;
    }
    $out .= "}\\\\\n";
    $out .= "\\IEEEauthorblockA{%\n";
    foreach ($affiliations[$aff] as $line)
    {
      $out .= $line."\\\\\n";
    }
    $out .= "}\n";
  }
  $out .= "}\n\n";
  $out .= "\\input{includes.tex}\n\n";
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= "\\begin{document}\n\n";
  $out .= "\\maketitle\n";
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  file_put_contents($out_folder."preamble-ieee.inc.tex", $out);
  
  // IEEE Journal: just replace conf by journal in documentclass
  $out = str_replace("\\documentclass[conference", "\\documentclass[journal", $out);
  $out .= "\n% Fixing bug in the definition of \\markboth in IEEEtran class\n% See http://tex.stackexchange.com/a/88864\n\\makeatletter\n\\let\\l@ENGLISH\\l@english\n\\makeatother\n";
  file_put_contents($out_folder."preamble-ieee-journal.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  $out .= "\\bibliography{".$config["bib-name"]."}\n";
  $out .= "\\input{appendices.tex}\n";
  $out .= "\\end{document}\n";
  file_put_contents($out_folder."postamble-ieee.inc.tex", $out);
  
  // IEEE Journal: samething
  file_put_contents($out_folder."postamble-ieee-journal.inc.tex", $out);
} // }}}

{ // ACM Conferences {{{
  
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "abbrv" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[{$point_size_string}]{sig-alternate-05-2015}

% Usual packages
\usepackage[utf8]{inputenc}  % UTF-8 input encoding
\usepackage[T1]{fontenc}     % Type1 fonts
\usepackage{lmodern}         % Improved Computer Modern{$microtype_string}
\usepackage[english]{babel}  % Hyphenation
\usepackage{graphicx}        % Import graphics
\usepackage{cite}            % Better handling of citations
\usepackage{hyperref}        % Better handling of references in PDFs
\usepackage{comment}         % To comment out blocks of text
EOD;
  if ($config["fix-acm"] === true)
  {
    $out .= "\\usepackage{fixacm}\n";
  }
  $out .= <<<EOD
% Fix ACM's awkward 2-column justification rules
\sloppy

\\input{includes.tex}

EOD;
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= <<<EOD
\\begin{document}

% Copyright
\\setcopyright{acmcopyright}
%\\setcopyright{acmlicensed}
%\\setcopyright{rightsretained}
%\\setcopyright{usgov}
%\\setcopyright{usgovmixed}
%\\setcopyright{cagov}
%\\setcopyright{cagovmixed}

% DOI
\\doi{{$config["doi"]}}

% ISBN and price
\\isbn{{$config["isbn"]}}
\\acmPrice{\\$15.00}

% Paper Metadata
\\conferenceinfo{{$config["conference"]}}{{$config["conference-loc"]}}
\\CopyrightYear{{$config["year"]}}
\\crdata{{$config["copyright"]}}  % Allows default copyright data (0-89791-88-6/97/05) to be over-ridden - IF NEED BE.
EOD;

  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n\n";
  
  // Group all authors with same affiliation
  $authors_aff = array();
  foreach ($authors as $name => $aff)
  {
    if (!isset($authors_aff[$aff]))
    {
      $authors_aff[$aff] = array();
    }
    $authors_aff[$aff][] = $name;
  }
  $out .= "% Authors and affiliations\n";
  $out .= "\\numberofauthors{".count($affiliations)."}\n";
  $out .= "\\author{%\n";
  foreach ($authors_aff as $aff => $names)
  {
    $first = true;
    $out .= "\\alignauthor ";
    foreach ($names as $name)
    {
      if ($first)
      {
        $first = false;
      }
      else
      {
        $out .= ", ";
      }
      $out .= $name;
    }
    $out .= "\\\\\n";
    foreach ($affiliations[$aff] as $line)
    {
      $out .= "\\affaddr{".$line."} \\\\\n";
    }
  }
  $out .= "}\n";
  $out .= "\\maketitle\n";
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  file_put_contents($out_folder."preamble-acm.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  $out .= "\\bibliography{".$config["bib-name"]."}\n";
  $out .= "\\input{appendices.tex}\n";
  $out .= "\\balancecolumns\n";
  $out .= "\\end{document}\n";
  file_put_contents($out_folder."postamble-acm.inc.tex", $out);
} // }}}

{ // Elsevier article {{{
  
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "elsarticle-num" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[preprint{$point_size_string_comma}]{elsarticle}

% Usual packages
\usepackage[utf8]{inputenc}  % UTF-8 input encoding
\usepackage[T1]{fontenc}     % Type1 fonts
\usepackage{lmodern}         % Improved Computer Modern font{$microtype_string}
\usepackage[english]{babel}  % Hyphenation
\usepackage{graphicx}        % Import graphics
\usepackage{hyperref}        % Better handling of references in PDFs
\usepackage{comment}         % To comment out blocks of text
\biboptions{sort&compress}   % Sort and compress citations

\journal{{$config["journal-name"]}}

% User-defined includes
\input includes.tex

EOD;
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= <<<EOD

\begin{document}

\begin{frontmatter}
EOD;

  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n\n";
  
  // Group all authors with same affiliation
  $out .= "% Authors and affiliations\n";
  foreach ($authors as $name => $aff)
  {
    $out .= "\\author{";
    $out .= $name."\\fnref{label".$aff."}";
    $out .= "}\n";
  }
  foreach ($affiliations as $key => $lines)
  {
    $out .= "\\fntext[label$key]{";
    $first = true;
    foreach ($lines as $line)
    {
      if ($first)
      {
        $first = false;
      }
      else
      {
        $out .= ", ";
      }
      $out .= $line;
    }
    $out .= "}\n";
  }
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  $out .= "\\end{frontmatter}\n";
  file_put_contents($out_folder."preamble-elsarticle.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  $out .= "\n\\section*{References}\n";
  $out .= "\\bibliography{".$config["bib-name"]."}\n";
  $out .= "\\input{appendices.tex}\n";
  $out .= "\\end{document}\n";
  file_put_contents($out_folder."postamble-elsarticle.inc.tex", $out);
} // }}}

{ // Springer journal {{{
  
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "abbrv" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[sttt{$point_size_string_comma}]{svjour} % Remove referee for final version

% Usual packages
\usepackage[utf8]{inputenc}  % UTF-8 input encoding
\usepackage[T1]{fontenc}     % Type1 fonts
\usepackage{mathptmx}        % Times font with math support{$microtype_string}
\usepackage[english]{babel}  % Hyphenation
\usepackage{graphicx}        % Import graphics
\usepackage{hyperref}        % Better handling of references in PDFs
\usepackage{comment}         % To comment out blocks of text

% User-defined includes
\input includes.tex

EOD;
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= <<<EOD

\begin{document}

EOD;

  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n\n";
  
  // Group all authors with same affiliation
  $out .= "% Authors and affiliations\n";
  // Group all authors with same affiliation
  $authors_aff = array();
  foreach ($authors as $name => $aff)
  {
    if (!isset($authors_aff[$aff]))
    {
      $authors_aff[$aff] = array();
    }
    $authors_aff[$aff][] = $name;
  }
  $out .= "% Authors and affiliations\n";
  $out .= "\\author{%\n";
  foreach ($authors_aff as $aff => $names)
  {
    $first = true;
    foreach ($names as $name)
    {
      if ($first)
      {
        $first = false;
      }
      else
      {
        $out .= ", ";
      }
      $out .= $name;
    }
    $out .= "\\\\\n";
    foreach ($affiliations[$aff] as $line)
    {
      $out .= $line."\\\\\n";
    }
  }
  $out .= "}\n";
  $out .= "\\titlerunning{".$title."}\n";
  $out .= "\\authorrunning{";
  foreach ($authors as $name => $aff)
  {
    // Only first author
    $out .= $name." \\textit{et al.}";
    break;
  }
  $out .= "}\n";
  $out .= "\n\\maketitle\n";
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  file_put_contents($out_folder."preamble-svjour.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  $out .= "\\bibliography{".$config["bib-name"]."}\n";
  $out .= "\\input{appendices.tex}\n";
  $out .= "\\end{document}\n";
  file_put_contents($out_folder."postamble-svjour.inc.tex", $out);
} // }}}

{ // AAAI {{{
  
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "aaai" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[letterpaper{$point_size_string_comma}]{article}

% Usual packages
\usepackage[utf8]{inputenc}  % UTF-8 input encoding
\usepackage{aaai}
\usepackage{mathptmx}
\usepackage{helvet}
\usepackage{courier}
\\frenchspacing
\setlength{\pdfpagewidth}{8.5in}
\setlength{\pdfpageheight}{11in}{$microtype_string}
\usepackage[english]{babel}  % Hyphenation
\usepackage{graphicx}        % Import graphics
\usepackage{cite}            % Better handling of citations
\usepackage{comment}         % To comment out blocks of text
\setcounter{secnumdepth}{0}

EOD;

  $out .= "\\pdfinfo{\n";
  $out .= " /Title (".$title.")\n";
  $out .= " /Author (";
  $first = true;
  foreach ($authors as $name => $aff)
  {
    if ($first)
    {
      $first = false;
    }
    else
    {
      $out .= ", ";
    }
    $out .= $name;
  }
  $out .= ")\n";
  $out .= "}\n";
  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n\n";
  $first_aff = true;
  $out .= "% Authors and affiliations\n";
  $out .= "\\author{%\n";
  foreach ($authors_aff as $aff => $names)
  {
    if (!$first_aff)
    {
      $out .= "\\And\n";
    }
    else
    {
      $first_aff = false;
    }
    $first = true;
    foreach ($names as $name)
    {
      if ($first)
      {
        $first = false;
      }
      else
      {
        $out .= " \\and ";
      }
      $out .= $name;
    }
    $out .= "\\\\\n";
    foreach ($affiliations[$aff] as $line)
    {
      $out .= $line."\\\\\n";
    }
  }
  $out .= "}\n\n";
  $out .= "\\input includes.tex\n\n";
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= "\\begin{document}\n\n";
  $out .= "\\maketitle\n";
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\begin{quote}\n";
    $out .= "\\input{abstract.tex}\n";
    $out .= "\\end{quote}\n\\end{abstract}\n";
  }
  file_put_contents($out_folder."preamble-aaai.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  $out .= "\\bibliography{".$config["bib-name"]."}\n";
  $out .= "\\input{appendices.tex}\n";
  $out .= "\\end{document}\n";
  file_put_contents($out_folder."postamble-aaai.inc.tex", $out);
} // }}}

{ // ACM "small trim" journals {{{
  
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "ACM-Reference-Format-Journals" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
$autogen_comment
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[prodmode,{$config["journal-name"]}{$point_size_string_comma}]{acmsmall}

% Usual packages
\usepackage[utf8]{inputenc}  % UTF-8 input encoding{$microtype_string}
\usepackage[english]{babel}  % Hyphenation
\usepackage{graphicx}        % Import graphics
\usepackage{comment}         % To comment out blocks of text

% Package to generate and customize Algorithm as per ACM style
\usepackage[ruled]{algorithm2e}
\\renewcommand{\algorithmcfname}{ALGORITHM}
\SetAlFnt{\small}
\SetAlCapFnt{\small}
\SetAlCapNameFnt{\small}
\SetAlCapHSkip{0pt}
\IncMargin{-\parindent}

% Metadata Information
\acmVolume{{$config["volume"]}}
\acmNumber{{$config["number"]}}
\acmArticle{{$config["article-number"]}}
\acmYear{{$config["year"]}}
\acmMonth{{$config["month"]}}

% DOI
\doi{{$config["doi"]}}

%ISSN
\issn{{$config["issn"]}}

% User-defined includes
\input includes.tex

EOD;
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= <<<EOD

\begin{document}

EOD;

  $out .= "\\title{".$title."}\n";
  $out .= "\\author{";
  foreach ($authors as $name => $aff)
  {
    $out .= mb_strtoupper($name, "UTF-8")."\n\\affil{";
    for ($i = 0; $i < count($affiliations[$aff]) - 1; $i++)
    {
      // We append all but the last line of each affiliation
      // (as this line generally contains a postal code that doesn't
      // belong here)
      $line = $affiliations[$aff][$i];
      if ($i > 0)
        $out .= ", ";
      $out .= $line;
    }
    $out .= "}\n";
  }
  $out .= "}\n";
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  $out .= "\\input acm-ccs.tex\n";
  $out .= "\n\\acmformat{";
  $out .= implode(", ", array_keys($authors));
  $out .= ", ".date("Y").". ".$title.".}\n";
  $out .= "\begin{bottomstuff}\\input{acm-bottom.tex}\n\\end{bottomstuff}\n";
  $out .= "\\maketitle\n";
  file_put_contents($out_folder."preamble-acm-journal.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  $out .= "\\bibliography{".$config["bib-name"]."}\n\n";
  $out .= "\\input{appendices.tex}\n";
  $out .= "% History dates\n\\received{".date("F Y")."}{".date("F Y")."}{".date("F Y")."}\n";
  $out .= "\\end{document}\n";
  file_put_contents($out_folder."postamble-acm-journal.inc.tex", $out);
}

// }}}

{ // EPTCS {{{
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "abbrv" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[submission,copyright,creativecommons{$point_size_string_comma}]{eptcs}

% Usual packages
\usepackage[utf8]{inputenc}  % UTF-8 input encoding
\usepackage[T1]{fontenc}     % Type1 fonts
\usepackage{lmodern}         % Improved Computer Modern font{$microtype_string}
\usepackage[english]{babel}  % Hyphenation
\usepackage{graphicx}        % Import graphics
\usepackage{cite}            % Better handling of citations
\usepackage{hyperref}        % Better handling of references in PDFs
\usepackage{comment}         % To comment out blocks of text
\usepackage{breakurl}        % Not needed if you use pdflatex only.
EOD;

  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n\n";
  
  // Group all authors with same affiliation
  $authors_aff = array();
  foreach ($authors as $name => $aff)
  {
    if (!isset($authors_aff[$aff]))
    {
      $authors_aff[$aff] = array();
    }
    $authors_aff[$aff][] = $name;
  }
  $out .= "% Authors and affiliations\n";
  $out .= "\\author{%\n";
  $first_aff = true;
  $au_running = array();
  foreach ($authors_aff as $aff => $names)
  {
    if ($first_aff)
    {
      $first_aff = false;
    }
    else
    {
      $out .= "\\and\n";
    }
    $first = true;
    foreach ($names as $name)
    {
      $au_running[] = initialize($name);
      if ($first)
      {
        $first = false;
      }
      else
      {
        $out .= ", ";
      }
      $out .= $name;
    }
    $out .= "\\institute{%\n";
    foreach ($affiliations[$aff] as $line)
    {
      $out .= $line."\\\\\n";
    }
    $out .= "}\n";
  }
  $out .= "}\n\n";
  $out .= "\\def\\titlerunning{".$title."}\n";
  $out .= "\\def\\authorrunning{".implode(", ", $au_running)."}\n";
  $out .= "\\input{includes.tex}\n\n";
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= "\\begin{document}\n\n";
  $out .= "\\maketitle\n";
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  file_put_contents($out_folder."preamble-eptcs.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  $out .= "\\bibliography{".$config["bib-name"]."}\n";
  $out .= "\\input{appendices.tex}\n";
  $out .= "\\end{document}\n";
  file_put_contents($out_folder."postamble-eptcs.inc.tex", $out);
} // }}}

{ // Wiley STVR {{{
  
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "wileyj" : $config["bib-style"];
  $short_title =  empty($config["short-title"]) ? $title : $config["short-title"];
  $doublespace = $config["doublespace"] ? "\\def\\baselinestretch{2}\n" : "";
  $authors_initials = "";
  $first = true;
  foreach ($authors as $name => $aff)
  {
    if ($first)
      $first = false;
    else
      $authors_initials .= ", ";
    $authors_initials .= initialize($name);
  }
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[times{$point_size_string_comma}]{stvrauth}

% Usual packages
\usepackage[utf8]{inputenc}  % UTF-8 input encoding
\usepackage[T1]{fontenc}     % Type1 fonts{$microtype_string}
\usepackage[english]{babel}  % Hyphenation
\usepackage{graphicx}        % Import graphics
\usepackage{cite}            % Better handling of citations
\usepackage{hyperref}        % Better handling of references in PDFs
\usepackage{comment}         % To comment out blocks of text
\usepackage{mathptmx}        % Times font with math support
{$doublespace}
EOD;

  $out .= "\n\n% Running heads\n";
  $out .= "\\runningheads{".$authors_initials."}{".$short_title."}\n\n";
  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n\n";
  
  $out .= "% Authors and affiliations\n";
  $out .= "\\author{";
  $first = true;
  foreach ($authors as $name => $aff)
  {
    if ($first)
    {
      $first = false;
    }
    else
    {
      $out .= ", ";
    }
    $out .= $name.(count($affiliations) < 2 ? "" : "\\affil{".$aff."}");
  }
  $out .= "}\n";
  $out .= "\\address{%\n";
  $first = true;
  $i = 0;
  foreach ($affiliations as $key => $lines)
  {
    $i++;
    if ($first)
    {
      $first = false;
    }
    else
    {
      $out .= "\\break\n";
    }
    $out .= "\\affilnum{$i}";
    $out .= implode(", ", $lines);
  }
  $out .= "}\n\n";
  $out .= "\\corraddr{".$config["corr-addr"]."}\n\n";
  $out .= "\\input{includes.tex}\n\n";
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= "\\begin{document}\n\n";
  $out .= "\\maketitle\n";
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  file_put_contents($out_folder."preamble-stvr.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  $out .= "\\bibliography{".$config["bib-name"]."}\n";
  $out .= "\\input{appendices.tex}\n";
  $out .= "\\end{document}\n";
  file_put_contents($out_folder."postamble-stvr.inc.tex", $out);
} // }}}

echo "\nDone. Go to the Source folder and type `make' to compile the paper.\n";

/**
 * Guesses an author's initials
 */
function initialize($name) // {{{
{
  if (strpos($name, "{") !== false)
  {
    $matches = array();
    preg_match("/\\{(.*?)\\}\\s*\\{(.*?)\\}/", $name, $matches);
    $first_names = $matches[1];
    $last_names = $matches[2];
    $names_array = explode(" ", $first_names);
    $ab_names = "";
    foreach ($names_array as $name)
    {
      $ab_names .= substr($name, 0, 1).".";
    }
    return $ab_names."\\ ".$last_names;
  }
  else
  {
    // If the user didn't break the name into first/last, guess
    $names = explode(" ", $name);
    $ab_names = "";
    for ($i = 0; $i < count($names) - 1; $i++)
    {
      $ab_names .= substr($names[$i], 0, 1).".";
    }
    return $ab_names."\\ ".$names[count($names) - 1];
  }

} // }}}

/**
 * Produces the graphicspath string from the array of paths
 * specified in the configuration
 */
function get_graphicspath() // {{{
{
  global $config;
  $out = "{";
  foreach ($config["graphicspath"] as $gp)
  {
    $out .= "{".$gp."}";
  }
  $out .= "}";
  return $out;
} // }}}

// :wrap=none:folding=explicit:
?>
