<?php
/**************************************************************************
  A Flexible LaTeX Article Environment
  Copyright (C) 2015-2022  Sylvain Hallé

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **************************************************************************/

// Version
$version_string = "2.6.1";
$autogen_comment = "%% This file was autogenerated by PaperShell v$version_string on ".date("Y-m-d H:i:s")."\n%% https://github.com/sylvainhalle/PaperShell\n%% DO NOT EDIT!";

// Read author-title file
$input_filename = "authors.txt";
$out_folder = "Source/";

// Read default config settings. All these settings can be modified with
// settings.inc.php. Do not modify them here.
$config = array(
	"style"           => "",
	"tex-name"        => "paper",
	"bib-name"        => "paper",
	"short-title"     => "",
	"point-size"      => null,
	"abstract"        => true,
	"journal-name"    => "Nuclear Physics B",
	"volume"          => 9,
	"number"          => 4,
	"article-number"  => 39,
	"conference"      => "OUTATIME '55",
	"conf-name"       => "42nd Conference on Very Important Topics",
	"conference-loc"  => "Hill Valley, CA, USA",
	"conference-date" => "November 1955",
	"copyright"       => "0-89791-88-6/97/05",
	"year"            => date("Y"),
	"month"           => date("m"),
	"doi"             => "0000001.0000001",
	"isbn"            => "123-4567-24-567/08/06",
	"issn"            => "1234-56789",
	"acm-class"       => "",
	"acm-number"      => "100",
	"acm-copyright"   => "none",
	"use-times"       => false,
	"bib-style"       => "",
	"graphicspath"    => array("fig/"),
	"microtype"       => true,
	"corr-addr"       => "Hill Valley University, CA",
	"doublespace"     => false,
	"disable-hr"      => false,
	"keywords"        => "time travel, flux capacitor",
	"otheropts"       => "",
	"easychair-type"  => ""
);
if (file_exists("settings.inc.php"))
{
  include("settings.inc.php");
}

// Just show version number; used by satellite scripts to show the same version
// as the main program
$to_set = "";
for ($i = 1; $i < count($argv); $i++)
{
	$arg = $argv[$i];
	if ($arg === "--show-version")
	{
		echo $version_string;
		exit(0);
	}
	$config["style"] = strtolower($arg);
}
$generated = false;
if ($config["style"] === "")
{
	// No style was provided. Stop.
	echo "No style has been provided. Usage:\n";
	echo "php set-style.php <style>\n";
	exit(1);
}

// Some setup based on config
$hr_draft = "";
if ($config["disable-hr"] == true)
{
  $hr_draft = ",draft";
}
$lines = explode("\n", file_get_contents($input_filename));

{ // Parse file {{{
  $has_title = false;
  $current_affiliation = 1;
  $title = "";
  $affiliations = array();
  $authors = array();
  foreach ($lines as $line)
  {
    $line = trim($line);
    if (empty($line) || $line[0] === "#")
    {
      continue;
    }
    if (!$has_title)
    {
      $title = $line;
      $has_title = true;
      continue;
    }
    $matches = array();
    if (preg_match("/^(.*?)\\(([\\d, ]+?)\\)(.*?)$/", $line, $matches))
    {
      $author_data = array("aff" => trim($matches[2]), "orcid" => "", "email" => "");
      $optional_part = trim($matches[3]);
      if ($optional_part !== "")
      {
      	  $parts = explode(",", $optional_part);
      	  $author_data["email"] = trim($parts[0]);
      	  if (count($parts) > 1)
      	  {
      	  	  $author_data["orcid"] = trim($parts[1]);
      	  }
      }
      $authors[trim($matches[1])] = $author_data;
    }
    elseif (preg_match("/^\\d+$/", $line))
    {
      $current_affiliation = $line;
    }
    else
    {
      if (!isset($affiliations[$current_affiliation]))
      {
        $affiliations[$current_affiliation] = array();
      }
      $affiliations[$current_affiliation][] = $line;
    }
  }
} // }}}

// Basic info
echo "PaperShell v".$version_string."\nA template environment for papers written in LaTeX\n(C) 2015-2021 Sylvain Hallé, Université du Québec à Chicoutimi\nhttps://github.com/sylvainhalle/PaperShell\n";

// Now that authors and affiliations are known, generate the preamble
// specific to each stylesheet

// Set a point-size, or use the default if not specified
$point_size_string = $config["point-size"] === null ? "" : $config["point-size"]."pt";
$point_size_string_comma = $config["point-size"] === null ? "" : ",".$config["point-size"]."pt";

// Microtype enabled?
$microtype_string ="";
if ($config["microtype"])
{
  $microtype_string = "\n\usepackage{microtype}       % Better handling of typo";
}

if ($config["style"] === "lncs")
{ // Springer LNCS {{{
  
  $generated = true;
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "splncs04" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[{$point_size_string}{$config["otheropts"]}]{llncs}

% Usual packages
\usepackage[utf8]{inputenc}      % UTF-8 input encoding
\usepackage[T1]{fontenc}         % Type1 fonts{$microtype_string}
\usepackage[english]{babel}      % Hyphenation
\usepackage{graphicx}            % Import graphics
\usepackage{cite}                % Better handling of citations
\usepackage[scaled]{helvet} % Scale Helvetica
\usepackage[bookmarks=false$hr_draft]{hyperref}            % Better handling of references in PDFs
\usepackage{comment}             % To comment out blocks of text
EOD;

  if ($config["use-times"])
  {
    $out .= "\n\\usepackage{newtxtext,newtxmath} % Times font with math support\n";
  }
  else
  {
    $out .= "\n\\usepackage{lmodern}             % Improved Computer Modern font\n";
  }

  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n\n";
  
  $out .= "% Authors and affiliations\n";
  $out .= "\\author{";
  $first = true;
  foreach ($authors as $name => $data)
  {
  	$aff = $data["aff"];
    if ($first)
    {
      $first = false;
    }
    else
    {
      $out .= " \\and ";
    }
    $out .= $name.(count($affiliations) < 2 ? "" : "\\inst{".$aff."}");
  }
  $out .= "%\n}\n";
  $out .= "\\institute{%\n";
  $first = true;
  foreach ($affiliations as $key => $lines)
  {
    if ($first)
    {
      $first = false;
    }
    else
    {
      $out .= "\\and\n";
    }
    $out .= implode(" \\\\\n", $lines);
  }
  $out .= "%\n}\n\n";
  $out .= "\\input{includes.tex}\n\n";
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= "\\begin{document}\n\n";
  $out .= "\\maketitle\n";
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  file_put_contents($out_folder."preamble.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  file_put_contents($out_folder."midamble.inc.tex", $out);
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\input{appendices.tex}\n";
  file_put_contents($out_folder."postamble.inc.tex", $out);
} // }}}

if ($config["style"] === "ieee-conf" || $config["style"] === "ieee-journal")
{ // IEEE Conference Proceedings and Journals {{{
  
  $generated = true;
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "abbrv" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[conference{$point_size_string_comma}{$config["otheropts"]}]{IEEEtran}
%FOO
% Usual packages
\usepackage[utf8]{inputenc}      % UTF-8 input encoding
\usepackage[T1]{fontenc}         % Type1 fonts
\usepackage[english]{babel}      % Hyphenation
\usepackage{graphicx}            % Import graphics
\usepackage{cite}                % Better handling of citations
\usepackage[scaled]{helvet} % Scale Helvetica
\usepackage[bookmarks=false$hr_draft]{hyperref}            % Better handling of references in PDFs
\usepackage{comment}             % To comment out blocks of text
EOD;

  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n\n";
  
  // Group all authors with same affiliation
  $authors_aff = array();
  foreach ($authors as $name => $data)
  {
  	$aff = $data["aff"];
    if (!isset($authors_aff[$aff]))
    {
      $authors_aff[$aff] = array();
    }
    $authors_aff[$aff][] = $name;
  }
  $out .= "% Authors and affiliations\n";
  $out .= "\\author{%\n";
  foreach ($authors_aff as $aff => $names)
  {
    $first = true;
    $out .= "\\IEEEauthorblockN{";
    foreach ($names as $name)
    {
      if ($first)
      {
        $first = false;
      }
      else
      {
        $out .= ", ";
      }
      $out .= $name;
    }
    $out .= "%\n}\n\\\\\n";
    $out .= "\\IEEEauthorblockA{%\n";
    foreach ($affiliations[$aff] as $line)
    {
      $out .= $line."\\\\\n";
    }
    $out .= "%\n}\n\n";
  }
  $out .= "%\n}\n\n";
  $out .= "\\input{includes.tex}\n\n";
  $out .= "\\usepackage{newtxtext,newtxmath} % Times with math support. Must be placed here to avoid clash if amsthm is loaded in includes{$microtype_string}\n";
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= "\\begin{document}\n\n";
  $out .= "\\maketitle\n";
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  file_put_contents($out_folder."preamble.inc.tex", $out);
  
  if ($config["style"] === "ieee-journal")
  {
  	  // IEEE Journal: just replace conf by journal in documentclass
  	  $out = str_replace("\\documentclass[conference", "\\documentclass[journal", $out);
  }
  $out .= "\n% Fixing bug in the definition of \\markboth in IEEEtran class\n% See http://tex.stackexchange.com/a/88864\n\\makeatletter\n\\let\\l@ENGLISH\\l@english\n\\makeatother\n";
  file_put_contents($out_folder."preamble.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  file_put_contents($out_folder."midamble.inc.tex", $out);
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\input{appendices.tex}\n";
  file_put_contents($out_folder."postamble.inc.tex", $out);
} // }}}

if ($config["style"] === "ieee-trans")
{ // IEEE Transactions {{{
  
  $generated = true;
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "abbrv" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[10pt,journal,compsoc{$config["otheropts"]}]{IEEEtran}
%FOO
% Usual packages
\usepackage[utf8]{inputenc}      % UTF-8 input encoding
\usepackage[T1]{fontenc}         % Type1 fonts
\usepackage[english]{babel}      % Hyphenation
\usepackage{graphicx}            % Import graphics
\usepackage{cite}                % Better handling of citations
\usepackage[scaled]{helvet} % Scale Helvetica
\usepackage[bookmarks=false$hr_draft]{hyperref}            % Better handling of references in PDFs
\usepackage{comment}             % To comment out blocks of text
EOD;
  $out .= "\n\n\\input{includes.tex}\n\n";
  $out .= "\n\n\\begin{document}\n\n";
  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n\n";
  
  // Group all authors with same affiliation
  $authors_aff = array();
  foreach ($authors as $name => $data)
  {
  	$aff = $data["aff"];
    if (!isset($authors_aff[$aff]))
    {
      $authors_aff[$aff] = array();
    }
    $authors_aff[$aff][] = $name;
  }
  $out .= "% Authors and affiliations\n";
  $out .= "\\author{%\n";
  foreach ($authors_aff as $aff => $names)
  {
    $first = true;
    foreach ($names as $name)
    {
      if ($first)
      {
        $first = false;
      }
      else
      {
        $out .= ", ";
      }
      $out .= $name;
    }
  }
  $out .= "\\IEEEcompsocitemizethanks{%\n";
  $first_item = true;
  foreach ($authors_aff as $aff => $names)
  {
  	if ($first_item)
  	{
  	  $first_item = false;
  	}
  	else
    {
  	  $out .= "\\protect\\\\\n";
  	}
  	$out .= "\\IEEEcompsocthanksitem ";
  	$first = true;
    foreach ($names as $name)
    {
      if ($first)
      {
        $first = false;
      }
      else
      {
        $out .= ", ";
      }
      $out .= $name;
    }
    if (count($names) > 1)
    {
    	$out .= " are with ";
    }
    else
    {
    	$out .= " is with ";
    }
    for ($i = 0; $i < count($affiliations[$aff]); $i++)
    {
    	if ($i > 0)
    	{
    		$out .= ", ";
    	}
    	$out .= $affiliations[$aff][$i];
    }
  }
  $out .= "}\n";
  $out .= "%\n}\n\n";
  $out .= "% Journal name\n";
  $out .= "\\markboth{".$config["journal-name"].",~Vol.~".$config["volume"].", No.~".$config["number"].", ".$config["month"]." ".$config["year"]."}%\n{}\n\n";
  //$out .= "\\usepackage{newtxtext,newtxmath} % Times with math support. Must be placed here to avoid clash if amsthm is loaded in includes{$microtype_string}\n";
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= "\\IEEEtitleabstractindextext{%\n";
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  $out .= "\\begin{IEEEkeywords}\n".$config["keywords"]."\n\\end{IEEEkeywords}\n";
  $out .= "}\n\n";
  $out .= "\\maketitle\n";
  $out .= "\\IEEEdisplaynontitleabstractindextext\n";
  $out .= "\\IEEEpeerreviewmaketitle\n";
  file_put_contents($out_folder."preamble.inc.tex", $out);
  
  if ($config["style"] === "ieee-journal")
  {
  	  // IEEE Journal: just replace conf by journal in documentclass
  	  $out = str_replace("\\documentclass[conference", "\\documentclass[journal", $out);
  }
  $out .= "\n% Fixing bug in the definition of \\markboth in IEEEtran class\n% See http://tex.stackexchange.com/a/88864\n\\makeatletter\n\\let\\l@ENGLISH\\l@english\n\\makeatother\n";
  file_put_contents($out_folder."preamble.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  file_put_contents($out_folder."midamble.inc.tex", $out);
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\input{appendices.tex}\n";
  file_put_contents($out_folder."postamble.inc.tex", $out);
} // }}}

if ($config["style"] === "ieee-cs-mag")
{ // IEEE Computer Society Magazine {{{
  
  $generated = true;
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "abbrv" : $config["bib-style"];
  $editor_name = empty($config["editor-name"]) ? "Stanford S.\\ Strickland" : $config["editor-name"];
  $editor_email = empty($config["editor-email"]) ? "strickland@hillvalley.edu" : $config["editor-email"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[conference{$point_size_string_comma}{$config["otheropts"]}]{IEEEcsmag}

% Usual packages
\usepackage[utf8]{inputenc}      % UTF-8 input encoding
\usepackage[T1]{fontenc}         % Type1 fonts
\usepackage[english]{babel}      % Hyphenation
\usepackage{graphicx}            % Import graphics
\usepackage{cite}                % Better handling of citations
\usepackage[scaled]{helvet}      % Scale Helvetica
\usepackage[colorlinks,urlcolor=blue,linkcolor=blue,citecolor=blue,bookmarks=false$hr_draft]{hyperref}            % Better handling of references in PDFs
\usepackage{comment}             % To comment out blocks of text
EOD;

  $out .= "\\jvol{".$config["volume"]."}\n";
  $out .= "\\jnum{".$config["number"]."}\n";
  $out .= "\\paper{".$config["article-number"]."}\n";
  $out .= "\\jmonth{".$config["month"]."}\n";
  $out .= "\\jname{".$config["journal-name"]."}\n";
  $out .= "\\pubyear{".$config["year"]."}\n";
  $out .= "\\setcounter{secnumdepth}{0}\n";
  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n\n";
  $out .= "\\input{includes.tex}\n\n";
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= "\\begin{document}\n\n";
  $out .= "\\sptitle{Department: Head}\n";
  $out .= "\\editor{Editor: ".$editor_name.", ".$editor_email."}\n";
  // Group all authors with same affiliation
  $authors_aff = array();
  foreach ($authors as $name => $data)
  {
  	$aff = $data["aff"];
    if (!isset($authors_aff[$aff]))
    {
      $authors_aff[$aff] = array();
    }
    $authors_aff[$aff][] = $name;
  }
  foreach ($authors_aff as $affno => $names)
  {
  	  $out .= "\\author{";
  	  for ($i = 0; $i < count($names); $i++)
  	  {
  	  	  if ($i > 0)
  	  	  {
  	  	  	  $out .= ", ";
  	  	  }
  	  	  $out .= $names[$i];
  	  }
  	  $out .= "}\n";
  	  $out .= "\\affil{";
  	  $afflines = $affiliations[$affno];
  	  for ($i = 0; $i < count($afflines); $i++)
  	  {
  	  	  if ($i > 0)
  	  	  {
  	  	  	  $out .= ", ";
  	  	  }
  	  	  $out .= $afflines[$i];
  	  }
  	  $out .= "}\n";
  }
  $out .= "\\markboth{".$title."}{}\n\n";
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  $out .= "\\maketitle\n";
  file_put_contents($out_folder."preamble.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  file_put_contents($out_folder."midamble.inc.tex", $out);
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\input{appendices.tex}\n";
  file_put_contents($out_folder."postamble.inc.tex", $out);
} // }}}

if ($config["style"] === "acmconf")
{ // ACM Conferences {{{
  
  $generated = true;
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "abbrv" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[sigconf,{$point_size_string}{$config["otheropts"]}]{acmart}

% Usual packages
\usepackage[utf8]{inputenc}  % UTF-8 input encoding
\usepackage[T1]{fontenc}     % Type1 fonts{$microtype_string}
\usepackage[english]{babel}  % Hyphenation
\usepackage{graphicx}        % Import graphics
\usepackage{comment}         % To comment out blocks of text
\usepackage{flushend}        % To balance columns on last page

% Copyright
\\setcopyright{{$config["acm-copyright"]}}

% DOI
\\acmDOI{{$config["doi"]}}

% ISBN and price
\\acmISBN{{$config["isbn"]}}
\\acmPrice{15.00}

% Paper Metadata
\\acmConference[{$config["conference"]}]{{$config["conf-name"]}}{{$config["conference-date"]}}{{$config["conference-loc"]}}
\\acmYear{{$config["year"]}}
\\copyrightyear{{$config["year"]}}

\\input{includes.tex}

EOD;
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= <<<EOD
\\begin{document}

EOD;

  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n";
  
  // Authors
  $authors_aff = array();
  foreach ($authors as $name => $data)
  {
  	$aff = $data["aff"];
    $out .= "\\author{".$name."}\n";
    $out .= "\\affiliation{\n";
    $out .= "  \\institution{";
    $first_line = true;
    foreach ($affiliations[$aff] as $line)
    {
    	if ($first_line)
    	{
    		$first_line = false;
    	}
    	else
    	{
    		$out .= "\\\\\n";
    	}
    	$out .= $line;
    }
    $out .= "}\n";
    if (isset($config["author-affiliations"][$aff-1]["streetaddress"]))
    {
      $out .= "  \\streetaddress{".$config["author-affiliations"][$aff-1]["streetaddress"]."}\n";
    }
    if (isset($config["author-affiliations"][$aff-1]["city"]))
    {
      $out .= "  \\city{".$config["author-affiliations"][$aff-1]["city"]."}\n";
    }
    if (isset($config["author-affiliations"][$aff-1]["state"]))
    {
      $out .= "  \\state{".$config["author-affiliations"][$aff-1]["state"]."}\n";
    }
    if (isset($config["author-affiliations"][$aff-1]["postcode"]))
    {
      $out .= "  \\postcode{".$config["author-affiliations"][$aff-1]["postcode"]."}\n";
    }
    if (isset($config["author-affiliations"][$aff-1]["country"]))
    {
      $out .= "  \\country{".$config["author-affiliations"][$aff-1]["country"]."}\n";
    }
    $out .= "}\n";
  }
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n\n";
  }
  $out .= "\\input{acm-ccs.tex}\n";
  $out .= "\\keywords{".$config["keywords"]."%\n}\n\n";
  $out .= "\\maketitle\n";
  file_put_contents($out_folder."preamble.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  file_put_contents($out_folder."midamble.inc.tex", $out);
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\input{appendices.tex}\n";
  file_put_contents($out_folder."postamble.inc.tex", $out);
} // }}}

if ($config["style"] === "elsevier")
{ // Elsevier article {{{
  
  $generated = true;
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "elsarticle-num" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[preprint{$point_size_string_comma}{$config["otheropts"]}]{elsarticle}

% Usual packages
\usepackage[utf8]{inputenc}  % UTF-8 input encoding
\usepackage[T1]{fontenc}     % Type1 fonts
\usepackage{lmodern}         % Improved Computer Modern font{$microtype_string}
\usepackage[scaled]{helvet} % Scale Helvetica
\usepackage[english]{babel}  % Hyphenation
\usepackage{graphicx}        % Import graphics
\usepackage[bookmarks=false$hr_draft]{hyperref}            % Better handling of references in PDFs
\usepackage{comment}         % To comment out blocks of text
\biboptions{sort&compress}   % Sort and compress citations

\journal{{$config["journal-name"]}}

% User-defined includes
\input{includes.tex}

EOD;
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= <<<EOD

\begin{document}

\begin{frontmatter}
EOD;

  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n\n";
  
  // Group all authors with same affiliation
  $out .= "% Authors and affiliations\n";
  foreach ($authors as $name => $data)
  {
  	$aff = $data["aff"];
    $out .= "\\author{";
    $out .= $name."\\fnref{label".$aff."}";
    $out .= "%\n}\n";
  }
  foreach ($affiliations as $key => $lines)
  {
    $out .= "\\fntext[label$key]{";
    $first = true;
    foreach ($lines as $line)
    {
      if ($first)
      {
        $first = false;
      }
      else
      {
        $out .= ", ";
      }
      $out .= $line;
    }
    $out .= "%\n}\n";
  }
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  $out .= "\\end{frontmatter}\n";
  file_put_contents($out_folder."preamble.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  $out .= "\n\\section*{References}\n";
  file_put_contents($out_folder."midamble.inc.tex", $out);
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\input{appendices.tex}\n";
  file_put_contents($out_folder."postamble.inc.tex", $out);
} // }}}

if ($config["style"] === "springer")
{ // Springer journal {{{
  
  $generated = true;
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "sn-basic" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[default,pdflatex,iicol{$config["otheropts"]}]{sn-jnl}

% Usual packages
\usepackage[utf8]{inputenc}      % UTF-8 input encoding
\usepackage[T1]{fontenc}         % Type1 fonts
\usepackage{lmodern}             % Improved Computer Modern font{$microtype_string}
\usepackage[english]{babel}      % Hyphenation
\usepackage{graphicx}            % Import graphics
\usepackage{comment}             % To comment out blocks of text
\usepackage[scaled]{helvet}      % Scale Helvetica

\jyear{{$config["year"]}}

% User-defined includes
\input{includes.tex}

EOD;
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= <<<EOD

\\raggedbottom
\begin{document}

EOD;

  $out .= "\n\n% Title\n";
  $out .= "\\title[".$title."]{".$title."}\n\n";
  
  // First list authors
  $out .= "% Authors and affiliations\n";
  $first_author = true;
  foreach ($authors as $name => $data)
  {
  	$out .= "\\author";
  	if ($first_author)
  	{
  		$out .= "*";
  		$first_author = false;
  	}
  	$out .= "[".$data["aff"]."]{";
  	$out .= "\\fnm{".$name."}}";
  	$out .= "\\email{".$data["email"]."}\n";
  }
  $first_aff = true;
  foreach ($affiliations as $aff_nb => $content)
  {
  	  $out .= "\\affil";
  	  if ($first_aff)
  	  {
  	  	  $first_aff = false;
  	  	  $out .= "*";
  	  }
  	  $out .= "[$aff_nb]{";
  	  foreach ($content as $line)
  	  {
  	  	  $out .= $line." ";
  	  }
  	  $out .= "}\n";
  }
  if ($config["abstract"])
  {
    $out .= "\\abstract{\n\\input{abstract.tex}}\n";
  }
  $out .= "\\keywords{".$config["keywords"]."}\n";
  $out .= "\n\\maketitle\n";
  file_put_contents($out_folder."preamble.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  file_put_contents($out_folder."midamble.inc.tex", $out);
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\input{appendices.tex}\n";
  file_put_contents($out_folder."postamble.inc.tex", $out);
} // }}}

if ($config["style"] === "aaai")
{ // AAAI {{{
  
  $generated = true;
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "aaai" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[letterpaper{$point_size_string_comma}{$config["otheropts"]}]{article}

% Usual packages
\usepackage[utf8]{inputenc}  % UTF-8 input encoding
\usepackage{aaai}
\usepackage[english]{babel}  % Hyphenation
\usepackage{newtxtext,newtxmath}
\usepackage[scaled]{helvet} % Scale Helvetica
\usepackage{courier}
\\frenchspacing
\setlength{\pdfpagewidth}{8.5in}
\setlength{\pdfpageheight}{11in}{$microtype_string}
\usepackage{graphicx}        % Import graphics
\usepackage{cite}            % Better handling of citations
\usepackage{comment}         % To comment out blocks of text
\setcounter{secnumdepth}{0}

EOD;

  $out .= "\\pdfinfo{\n";
  $out .= " /Title (".$title.")\n";
  $out .= " /Author (";
  $first = true;
  foreach ($authors as $name => $data)
  {
  	$aff = $data["aff"];
    if ($first)
    {
      $first = false;
    }
    else
    {
      $out .= ", ";
    }
    $out .= $name;
  }
  $out .= ")\n";
  $out .= "}\n";
  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n\n";
  $first_aff = true;
  $out .= "% Authors and affiliations\n";
  $out .= "\\author{%\n";
  foreach ($authors_aff as $aff => $names)
  {
    if (!$first_aff)
    {
      $out .= "\\And\n";
    }
    else
    {
      $first_aff = false;
    }
    $first = true;
    foreach ($names as $name)
    {
      if ($first)
      {
        $first = false;
      }
      else
      {
        $out .= " \\and ";
      }
      $out .= $name;
    }
    $out .= "\\\\\n";
    foreach ($affiliations[$aff] as $line)
    {
      $out .= $line."\\\\\n";
    }
  }
  $out .= "%\n}\n\n";
  $out .= "\\input{includes.tex}\n\n";
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= "\\begin{document}\n\n";
  $out .= "\\maketitle\n";
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\begin{quote}\n";
    $out .= "\\input{abstract.tex}\n";
    $out .= "\\end{quote}\n\\end{abstract}\n";
  }
  file_put_contents($out_folder."preamble.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  file_put_contents($out_folder."midamble.inc.tex", $out);
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\input{appendices.tex}\n";
  file_put_contents($out_folder."postamble.inc.tex", $out);
} // }}}

if ($config["style"] === "acmjour")
{ // ACM "small trim" journals {{{
  
  $generated = true;
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "ACM-Reference-Format-Journals" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
$autogen_comment
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[format=acmsmall{$config["otheropts"]}]{acmart}

% Usual packages
\usepackage[utf8]{inputenc}     % UTF-8 input encoding{$microtype_string}
\usepackage[english]{babel}     % Hyphenation
\usepackage{graphicx}           % Import graphics
\usepackage{comment}            % To comment out blocks of text

% Package to generate and customize Algorithm as per ACM style
\usepackage[ruled]{algorithm2e}
\\renewcommand{\algorithmcfname}{ALGORITHM}
\SetAlFnt{\small}
\SetAlCapFnt{\small}
\SetAlCapNameFnt{\small}
\SetAlCapHSkip{0pt}
\IncMargin{-\parindent}

% Metadata Information
\acmJournal{{$config["journal-name"]}}
\acmVolume{{$config["volume"]}}
\acmNumber{{$config["number"]}}
\acmArticle{{$config["article-number"]}}
\acmYear{{$config["year"]}}
\acmMonth{{$config["month"]}}
\copyrightyear{{$config["year"]}}

% Copyright
\\setcopyright{{$config["acm-copyright"]}}

% DOI
\acmDOI{{$config["doi"]}}

% User-defined includes
\input{includes.tex}

EOD;
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= "%% Command for keywords\n\\newcommand{\\papershellkw}{".$config["keywords"]."%\n}\n\n";
  $out .= <<<EOD

\begin{document}

EOD;

  $out .= "\\title{".$title."}\n";
  // Authors
  $authors_aff = array();
  foreach ($authors as $name => $data)
  {
  	$aff = $data["aff"];
    $out .= "\\author{".$name."}\n";
    $out .= "\\affiliation{\n";
    $out .= "  \\institution{".$affiliations[$aff][0]."}\n";
    if (isset($config["author-affiliations"][$aff-1]["streetaddress"]))
    {
      $out .= "  \\streetaddress{".$config["author-affiliations"][$aff-1]["streetaddress"]."}\n";
    }
    if (isset($config["author-affiliations"][$aff-1]["city"]))
    {
      $out .= "  \\city{".$config["author-affiliations"][$aff-1]["city"]."}\n";
    }
    if (isset($config["author-affiliations"][$aff-1]["state"]))
    {
      $out .= "  \\state{".$config["author-affiliations"][$aff-1]["state"]."}\n";
    }
    if (isset($config["author-affiliations"][$aff-1]["postcode"]))
    {
      $out .= "  \\postcode{".$config["author-affiliations"][$aff-1]["postcode"]."}\n";
    }
    if (isset($config["author-affiliations"][$aff-1]["country"]))
    {
      $out .= "  \\country{".$config["author-affiliations"][$aff-1]["country"]."}\n";
    }
    $out .= "}\n";
  }
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n\n";
  }
  $out .= "\\input{acm-ccs.tex}\n";
  $out .= "\\keywords{".$config["keywords"]."%\n}\n\n";
  $out .= "\\maketitle\n";
  file_put_contents($out_folder."preamble.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\input{acm-bottom.tex}\n";
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  file_put_contents($out_folder."midamble.inc.tex", $out);
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\input{appendices.tex}\n";
  $out .= "% History dates\n\\received{".date("F Y")."}{".date("F Y")."}{".date("F Y")."}\n";
  file_put_contents($out_folder."postamble.inc.tex", $out);
}

// }}}

if ($config["style"] === "eptcs")
{ // EPTCS {{{
  
  $generated = true;
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "abbrv" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[submission,copyright,creativecommons{$point_size_string_comma}{$config["otheropts"]}]{eptcs}

% Usual packages
\usepackage[utf8]{inputenc}  % UTF-8 input encoding
\usepackage[T1]{fontenc}     % Type1 fonts
\usepackage{lmodern}         % Improved Computer Modern font{$microtype_string}
\usepackage[english]{babel}  % Hyphenation
\usepackage{graphicx}        % Import graphics
\usepackage{cite}            % Better handling of citations
\usepackage[bookmarks=false$hr_draft]{hyperref}            % Better handling of references in PDFs
\usepackage{comment}         % To comment out blocks of text
\usepackage{breakurl}        % Not needed if you use pdflatex only.
\usepackage[scaled]{helvet} % Scale Helvetica

EOD;

  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n\n";
  
  // Group all authors with same affiliation
  $authors_aff = array();
  foreach ($authors as $name => $data)
  {
  	$aff = $data["aff"];
    if (!isset($authors_aff[$aff]))
    {
      $authors_aff[$aff] = array();
    }
    $authors_aff[$aff][] = $name;
  }
  $out .= "% Authors and affiliations\n";
  $out .= "\\author{%\n";
  $first_aff = true;
  $au_running = array();
  foreach ($authors_aff as $aff => $names)
  {
    if ($first_aff)
    {
      $first_aff = false;
    }
    else
    {
      $out .= "\\and\n";
    }
    $first = true;
    foreach ($names as $name)
    {
      $au_running[] = initialize($name);
      if ($first)
      {
        $first = false;
      }
      else
      {
        $out .= ", ";
      }
      $out .= $name;
    }
    $out .= "\\institute{%\n";
    foreach ($affiliations[$aff] as $line)
    {
      $out .= $line."\\\\\n";
    }
    $out .= "%\n}\n";
  }
  $out .= "%\n}\n\n";
  $out .= "\\def\\titlerunning{".$title."}\n";
  $out .= "\\def\\authorrunning{".implode(", ", $au_running)."}\n";
  $out .= "\\input{includes.tex}\n\n";
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= "\\begin{document}\n\n";
  $out .= "\\maketitle\n";
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  file_put_contents($out_folder."preamble.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  file_put_contents($out_folder."midamble.inc.tex", $out);
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\input{appendices.tex}\n";
  file_put_contents($out_folder."postamble.inc.tex", $out);
} // }}}

if ($config["style"] === "stvr")
{ // Wiley STVR {{{
  
  $generated = true;
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "wileyj" : $config["bib-style"];
  $short_title =  empty($config["short-title"]) ? $title : $config["short-title"];
  $doublespace = $config["doublespace"] ? "\\def\\baselinestretch{2}\n" : "";
  $authors_initials = "";
  $first = true;
  foreach ($authors as $name => $data)
  {
  	$aff = $data["aff"];
    if ($first)
      $first = false;
    else
      $authors_initials .= ", ";
    $authors_initials .= initialize($name);
  }
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[times{$point_size_string_comma}{$config["otheropts"]}]{stvrauth}

% Usual packages
\usepackage[utf8]{inputenc}      % UTF-8 input encoding
\usepackage[T1]{fontenc}         % Type1 fonts{$microtype_string}
\usepackage[english]{babel}      % Hyphenation
\usepackage{graphicx}            % Import graphics
\usepackage{cite}                % Better handling of citations
\usepackage[bookmarks=false$hr_draft]{hyperref}            % Better handling of references in PDFs
\usepackage{comment}             % To comment out blocks of text
\usepackage{newtxtext,newtxmath} % Times font with math support
\usepackage[scaled]{helvet} % Scale Helvetica
{$doublespace}

\\newcommand\\BibTeX{{\\rmfamily B\\kern-.05em \\textsc{i\\kern-.025em b}\\kern-.08em
T\\kern-.1667em\\lower.7ex\\hbox{E}\\kern-.125emX}}

EOD;

  $out .= "\\def\\volumeyear{".$config["year"]."}\n\n";
  $out .= "\\input{includes.tex}\n\n";
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= "\n\\begin{document}\n\n";
  $out .= "\n\n% Running heads\n";
  $out .= "\\runningheads{".$authors_initials."}{".$short_title."}\n\n";
  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n\n";
  
  $out .= "% Authors and affiliations\n";
  $out .= "\\author{";
  $first = true;
  foreach ($authors as $name => $data)
  {
  	$aff = $data["aff"];
    if ($first)
    {
      $first = false;
    }
    else
    {
      $out .= ", ";
    }
    $out .= $name.(count($affiliations) < 2 ? "" : "\\affil{".$aff."}");
  }
  $out .= "%\n}\n";
  $out .= "\\address{%\n";
  $first = true;
  $i = 0;
  foreach ($affiliations as $key => $lines)
  {
    $i++;
    if ($first)
    {
      $first = false;
    }
    else
    {
      $out .= "\\break\n";
    }
    $out .= "\\affilnum{$i}";
    $out .= implode(", ", $lines);
  }
  $out .= "%\n}\n\n";
  $out .= "\\corraddr{".$config["corr-addr"]."}\n\n";
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  $out .= "\n\\keywords{".$config["keywords"]."}\n\n";
  $out .= "\n\\maketitle\n";
  file_put_contents($out_folder."preamble.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  file_put_contents($out_folder."midamble.inc.tex", $out);
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\input{appendices.tex}\n";
  file_put_contents($out_folder."postamble.inc.tex", $out);
} // }}}

if ($config["style"] === "lipics")
{ // LIPIcs {{{
  
  $generated = true;
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "plainurl" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[letterpaper,USenglish{$point_size_string_comma}{$config["otheropts"]}]{lipics-v2021}

% Usual packages
\usepackage[utf8]{inputenc}  % UTF-8 input encoding
\usepackage[T1]{fontenc}     % Type1 fonts
\usepackage{lmodern}         % Improved Computer Modern font{$microtype_string}
\usepackage{graphicx}        % Import graphics
\usepackage{comment}         % To comment out blocks of text
\usepackage[scaled]{helvet} % Scale Helvetica
\hypersetup{ % Since hyperref is already loaded by lipics
  bookmarks=false
}

% User-defined includes
\input{includes.tex}

EOD;

  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n";
  $out .= "\\titlerunning{".$title."}\n\n";
  
  // Group all authors with same affiliation
  $out .= "% Authors and affiliations\n";
  $au_running = array();
  foreach ($authors as $name => $data)
  {
  	$aff = $data["aff"];
  	$au_running[] = initialize($name);
    $out .= "\\author{".$name."}{";
    $lines = $affiliations[$aff];
    $first = true;
    foreach ($lines as $line)
    {
      if ($first)
      {
        $first = false;
      }
      else
      {
        $out .= ", ";
      }
      $out .= $line;
    }
    $out .= "}";
    $out .= "{".$data["email"]."}"; // Author-email
    $out .= "{".$data["orcid"]."}"; // Author ORCID
    $out .= "{}"; // Author funding acknowledgments
    $out .= "\n\n";
  }
  $out .= "\\authorrunning{".implode(", ", $au_running)."}\n";
  $out .= "\\Copyright{".implode(", ", $au_running)."}\n\n";
  $out .= "\\ccsdesc[100]{\\textcolor{red}{".$config["acm-class"]."}}\n\n";
  $out .= "\\keywords{".$config["keywords"]."%\n}\n\n";
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= "% Editor-only macros:: begin (do not touch as author)%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n";
  $out .= "\\EventEditors{John Q. Open and Joan R. Public}\n";
  $out .= "\\EventNoEds{2}\n";
  $out .= "\\EventLongTitle{".$config["conf-name"]." (".$config["conference"].")}\n";
  $out .= "\\EventShortTitle{".$config["conference"]."}\n";
  $out .= "\\EventAcronym{".explode(" ", $config["conference"])[1]."}\n";
  $out .= "\\EventYear{".$config["year"]."}\n";
  $out .= "\\EventDate{".$config["conference-date"]."}\n";
  $out .= "\\EventLocation{".$config["conference-loc"]."}\n";
  $out .= "\\EventLogo{}\n";
  $out .= "\\SeriesVolume{".$config["volume"]."}\n";
  $out .= "\\ArticleNo{".$config["number"]."}\n";
  $out .= "% Editor-only macros::end %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n";
  $out .= <<<EOD

\\begin{document}

\\maketitle

EOD;

  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  file_put_contents($out_folder."preamble.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  $out .= "% NOTE: the plainurl style is available in Ubuntu using texlive-bibtex-extra\n";
  file_put_contents($out_folder."midamble.inc.tex", $out);
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\input{appendices.tex}\n";
  file_put_contents($out_folder."postamble.inc.tex", $out);
} // }}}

if ($config["style"] === "easychair")
{ // EasyChair Proceedings {{{
  
  $generated = true;
  $easychair_type_string = "";
  if (!empty($config["easychair-type"]))
  {
    $easychair_type_string = ",".$config["easychair-type"];
  }
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "splncs04" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[{$point_size_string}{$easychair_type_string}{$config["otheropts"]}]{easychair}

% Usual packages
\usepackage[utf8]{inputenc}      % UTF-8 input encoding
\usepackage[T1]{fontenc}         % Type1 fonts{$microtype_string}
\usepackage[english]{babel}      % Hyphenation
%\usepackage{graphicx}           % Already loaded by document class
\usepackage{cite}                % Better handling of citations
\usepackage[scaled]{helvet}      % Scale Helvetica
\usepackage[bookmarks=false$hr_draft]{hyperref}            % Better handling of references in PDFs
\usepackage{comment}             % To comment out blocks of text
EOD;

  if ($config["use-times"])
  {
    $out .= "\n\\usepackage{newtxtext,newtxmath} % Times font with math support\n";
  }
  else
  {
    $out .= "\n\\usepackage{lmodern}             % Improved Computer Modern font\n";
  }

  $out .= "\n\n% Title\n";
  $out .= "\\title{".$title."}\n\n";
  
  $out .= "% Authors and affiliations\n";
  $out .= "\\author{";
  $first = true;
  foreach ($authors as $name => $data)
  {
  	$aff = $data["aff"];
    if ($first)
    {
      $first = false;
    }
    else
    {
      $out .= " \\and ";
    }
    $out .= $name.(count($affiliations) < 2 ? "" : "\\inst{".$aff."}");
  }
  $out .= "%\n}\n";
  $out .= "\\institute{%\n";
  $first = true;
  foreach ($affiliations as $key => $lines)
  {
    if ($first)
    {
      $first = false;
    }
    else
    {
      $out .= "\\and\n";
    }
    $out .= implode(" \\\\\n", $lines);
  }
  $out .= "%\n}\n\n";
  $out .= "% \\titlerunning{} has to be set to either the main title or its shorter\n% version for the running heads. When processed by\n% EasyChair, this command is mandatory: a document without \\titlerunning% will be rejected by EasyChair\n";
  $out .= "\\titlerunning{".$title."}\n";
  $out .= "% \\authorrunning{} has to be set for the shorter version of the authors' names;\n% otherwise a warning will be rendered in the running heads. When processed by\n% EasyChair, this command is mandatory: a document without \\authorrunning\n% will be rejected by EasyChair\n";
  $out .= "\\authorrunning{";
  foreach ($authors as $name => $data)
  {
  	$aff = $data["aff"];
    // Only first author
    $out .= $name." \\textit{et al.}";
    break;
  }
  $out .= "%\n}\n";
  $out .= "\\input{includes.tex}\n\n";
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= "\\begin{document}\n\n";
  $out .= "\\maketitle\n";
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  file_put_contents($out_folder."preamble.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  file_put_contents($out_folder."midamble.inc.tex", $out);
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\input{appendices.tex}\n";
  file_put_contents($out_folder."postamble.inc.tex", $out);
} // }}}

if ($config["style"] === "usenix")
{ // USENIX {{{
  
  $generated = true;
  // Preamble
  $bib_style = empty($config["bib-style"]) ? "plain" : $config["bib-style"];
  $out = "";
  $out .= <<<EOD
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[letterpaper,twocolumn,10pt{$config["otheropts"]}]{article}
\usepackage{usenix2019_v3}

% Usual packages
\usepackage[english]{babel}      % Hyphenation
\usepackage{graphicx}            % Import graphics
\usepackage[scaled]{helvet} % Scale Helvetica
\usepackage{comment}             % To comment out blocks of text
EOD;

  $out .= "\n\n% Title\n";
  $out .= "\\title{\\Large \\bf ".$title."}\n\n";
  
  $out .= "% Authors and affiliations\n";
  $out .= "\\author{\n";
  $first = true;
  foreach ($authors as $name => $data)
  {
  	$aff = $data["aff"];
    if ($first)
    {
      $first = false;
    }
    else
    {
      $out .= " \\and ";
    }
    $out .= "{\\rm $name}\\\\\n";
    $lines = $affiliations[$aff];
    $out .= implode(" \\\\\n", $lines);
  }
  $out .= "%\n}\n\n";
  $out .= "\\input{includes.tex}\n\n";
  $out .= "%% Default path for graphics\n\\graphicspath".get_graphicspath()."\n\n";
  $out .= "\\begin{document}\n\n";
  $out .= "\\maketitle\n";
  if ($config["abstract"])
  {
    $out .= "\\begin{abstract}\n\\input{abstract.tex}\n\\end{abstract}\n";
  }
  file_put_contents($out_folder."preamble.inc.tex", $out);
  
  // Postamble
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\bibliographystyle{".$bib_style."}\n";
  file_put_contents($out_folder."midamble.inc.tex", $out);
  $out = "";
  $out .= <<<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{$autogen_comment}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOD;
  $out .= "\n\\input{appendices.tex}\n";
  file_put_contents($out_folder."postamble.inc.tex", $out);
} // }}}

if ($generated)
{
	echo "\nGenerated ".$config["style"]." preamble and postamble.\n";
	echo "Go to the Source folder and type `make' to compile the paper.\n";
	exit(0);
}
else
{
	echo "\nInvalid style. Available styles are: lncs, ieee-conf, ieee-journal,\n";
	echo "ieee-trans, ieee-cs-mag, acmconf, elsevier, springer, aaai, acmjour,\n";
	echo "eptcs, stvr, lipics, easychair, usenix.\n";
	exit(1);
}

/**
 * Guesses an author's initials
 */
function initialize($name) // {{{
{
  if (strpos($name, "{") !== false)
  {
    $matches = array();
    preg_match("/\\{(.*?)\\}\\s*\\{(.*?)\\}/", $name, $matches);
    $first_names = $matches[1];
    $last_names = $matches[2];
    $names_array = explode(" ", $first_names);
    $ab_names = "";
    foreach ($names_array as $name)
    {
      $ab_names .= substr($name, 0, 1).".";
    }
    return $ab_names."\\ ".$last_names;
  }
  else
  {
    // If the user didn't break the name into first/last, guess
    $names = explode(" ", $name);
    $ab_names = "";
    for ($i = 0; $i < count($names) - 1; $i++)
    {
      $ab_names .= substr($names[$i], 0, 1).".";
    }
    return $ab_names."\\ ".$names[count($names) - 1];
  }

} // }}}

/**
 * Produces the graphicspath string from the array of paths
 * specified in the configuration
 */
function get_graphicspath() // {{{
{
  global $config;
  $out = "{";
  foreach ($config["graphicspath"] as $gp)
  {
    $out .= "{".$gp."}";
  }
  $out .= "}";
  return $out;
} // }}}

// :wrap=none:folding=explicit:
?>
