%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% This file was autogenerated by PaperShell v3 
%% https://github.com/sylvainhalle/PaperShell
%% DO NOT EDIT!
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[a4paper,fleqn]{sty/cas/cas-sc}

% Usual packages
\usepackage[utf8]{inputenc}            % UTF-8 input encoding
\usepackage[english]{babel}            % Hyphenation
\usepackage{graphicx}                  % Import graphics
\usepackage{cite}                      % Better handling of citations
\usepackage{comment}                   % To comment out blocks of text
\usepackage{flushend}                  % To balance columns on last page
\usepackage{microtype}                 % Better typesetting
\usepackage[numbers]{natbib}           % Citations

\input{includes.tex}

% Default path for graphicspath
\graphicspath{{fig/}}

\usepackage{etoolbox}

\makeatletter
\newread\CAS@absin
\newwrite\CAS@absout

\newcommand{\CASCopyFile}[2]{%
  \begingroup
    \openin\CAS@absin=#1\relax
    \immediate\openout\CAS@absout=#2\relax
    \loop\unless\ifeof\CAS@absin
      \read\CAS@absin to \CAS@line
      \immediate\write\CAS@absout{\unexpanded\expandafter{\CAS@line}}%
    \repeat
    \immediate\closeout\CAS@absout
    \closein\CAS@absin
  \endgroup
}

\newcommand{\setexternalabstract}[1]{%
  \pretocmd{\maketitle}{\CASCopyFile{#1}{\jobname.abs}}{}{}%
}

% Tell cas-sc that the abstract comes from an external file
\renewenvironment{abstract}{}{}
\makeatother

\setexternalabstract{abstract.tex}

\begin{document}
\let\WriteBookmarks\relax
\def\floatpagepagefraction{1}
\def\textpagefraction{.001}

% Short title
\shorttitle{%
<< title or "" >>%
}

% Short author
\shortauthors{%
}

% Authors and affiliations
<% for i,a in util.spairs(authors) do %>
\author[<<a.affiliation>>]{%
<< a.name >>%
}[<% if a.orcid then %> orcid=<<a.orcid>> <% end %>]
<% if a.corresponding then %>
\cormark[<<i>>]
<% end %>
%\fnmark{<<a.affiliation>>}
\ead{<<a.email>>}
<% end %>

<% for i,a in util.spairs(institutions) do %>
\affiliation[<<i>>]{
  organization={<<a.name>>},
  city={<<a.city>>},
  country={<<a.country>>}
}
<% end %>

% Main title of the paper
\title [ mode = title ]{%
<< title or "" >>%
}

\begin{abstract}
\end{abstract}

\begin{highlights}
\item FOO
\end{highlights}

\begin{keywords}
<< keywords:gsub(", ", " \\sep ") or "" >>%
\end{keywords}

\maketitle

%:mode=latex: