%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% This file was autogenerated by PaperShell v3 
%% https://github.com/sylvainhalle/PaperShell
%% DO NOT EDIT!
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[acmsmall]{sty/acmart/acmart}

% Usual packages
\usepackage[utf8]{inputenc}  % UTF-8 input encoding
\usepackage[english]{babel}  % Hyphenation
\usepackage{graphicx}        % Import graphics
\usepackage{comment}         % To comment out blocks of text
\usepackage{flushend}        % To balance columns on last page
\usepackage{microtype}       % Better typesetting

\input{includes.tex}

\begin{document}


\title{%
<< title or "" >>%
}

% Default path for graphicspath
\graphicspath{fig/}

\begin{abstract}
\input{abstract.tex}
\end{abstract}

%\input{acm-ccs.tex}
\keywords{%
<< keywords or "" >>%
}
\maketitle
%:mode=latex: