%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% This file was autogenerated by PaperShell v3 
%% https://github.com/sylvainhalle/PaperShell
%% DO NOT EDIT!
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass{sty/lncs/llncs}

% Usual packages
\usepackage[utf8]{inputenc}            % UTF-8 input encoding
\RequirePackage{iftex}
\ifLuaTeX
\usepackage{fontspec}
\else
\usepackage[T1]{fontenc}
\fi
\usepackage[english]{babel}            % Hyphenation
\usepackage{graphicx}                  % Import graphics
\usepackage{cite}                      % Better handling of citations
\usepackage{comment}                   % To comment out blocks of text
\usepackage{microtype}                 % Better typesetting
<% if options.times then %>
\usepackage{newtxtext,newtxmath}       % Improved Times font
<% else %>
\usepackage{lmodern}                   % Improved Computer Modern font
<% end %>

\input{includes.tex}

% Default path for graphicspath
\graphicspath{{fig/}}

% Authors and affiliations
\author{<% for i,a in util.spairs(authors) do
  if i ~= "1" then %>\and<% end %>
  << a.name >>\inst{<< a.affiliation or "1" >>}
<% end %>
}
\institute{<% for i,a in util.spairs(institutions) do
    if i ~= "1" then %>\and<% end %>
  << a.name >>\\
  << a.city >>, << a.country >>
<% end %>}

% Main title of the paper
\title{%
<< title >>%
}

\begin{document}

\maketitle

\begin{abstract}
\input{abstract.tex}
\end{abstract}

%:mode=latex: